app = "final-project-fall-2023-vienna-austria"
primary_region = "otp"

# Apps without volume: Comment out the [mounts] configuration below
[mounts]
  source = "postgres"
  destination = "/postgres-volume"

[env]
  PORT = "8080"
  CLOUDINARY_API_KEY="458685933649492"
  CLOUDINARY_API_SECRET="qXqXnijW6aLL_TkhHTLUGMH8XL4"
  DATABASE_URL="postgresql://final_project_fall_2023_vienna_austria:final_project_fall_2023_vienna_austria@localhost:5432/final_project_fall_2023_vienna_austria"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
